@db
Feature:Verify the answer from db

  Scenario Outline:Verify fourth question
    Given we are given "<film_id>" and "<title>"

    Examples:
      | film_id | title                       |
      | 1       | Academy Dinosaur            |
      | 4       | Affair Prejudice            |
      | 10      | Aladdin Calendar            |
      | 11      | Alamo Videotape             |
      | 19      | Amadeus Holy                |
      | 22      | Amistad Midsummer           |
      | 24      | Analyze Hoosiers            |
      | 25      | Angels Life                 |
      | 27      | Anonymous Human             |
      | 31      | Apache Divine               |
      | 35      | Arachnophobia Rollercoaster |
      | 37      | Arizona Bang                |
      | 45      | Attraction Newton           |
      | 55      | Barbarella Streetcar        |
      | 57      | Basic Easy                  |
      | 61      | Beauty Grease               |
      | 69      | Beverly Outlaw              |
      | 72      | Bill Others                 |
      | 73      | Bingo Talented              |
      | 77      | Birds Perdition             |
      | 80      | Blanket Beverly             |
      | 81      | Blindness Gun               |
      | 84      | Boiled Dares                |
      | 86      | Boogie Amelie               |
      | 91      | Bound Cheaper               |
      | 97      | Bride Intrigue              |
      | 100     | Brooklyn Desert             |
      | 101     | Brotherhood Blanket         |
      | 103     | Bucket Brotherhood          |
      | 109     | Butterfly Chocolat          |
      | 110     | Cabin Flash                 |
      | 112     | Calendar Gunfight           |
      | 114     | Camelot Vacation            |
      | 117     | Candles Grapes              |
      | 118     | Canyon Stock                |
      | 122     | Carrie Bunch                |
      | 127     | Cat Coneheads               |
      | 131     | Center Dinosaur             |
      | 132     | Chainsaw Uptown             |
      | 139     | Chasing Fight               |
      | 143     | Chill Luck                  |
      | 152     | Circus Youth                |
      | 153     | Citizen Shrek               |
      | 159     | Closer Bang                 |
      | 166     | Color Philadelphia          |
      | 167     | Coma Head                   |
      | 172     | Coneheads Smoochy           |
      | 174     | Confidential Interview      |
      | 179     | Conquerer Nuts              |
      | 193     | Crossroads Casualties       |
      | 199     | Cupboard Sinners            |
      | 200     | Curtain Videotape           |
      | 201     | Cyclone Family              |
      | 204     | Dalmations Sweden           |
      | 205     | Dances None                 |
      | 206     | Dancing Fever               |
      | 207     | Dangerous Uptown            |
      | 209     | Darkness War                |
      | 213     | Date Speed                  |
      | 218     | Deceiver Betrayed           |
      | 219     | Deep Crusade                |
      | 220     | Deer Virginian              |
      | 231     | Dinosaur Secretary          |
      | 233     | Disciple Mother             |
      | 234     | Disturbing Scarface         |
      | 239     | Dogma Family                |
      | 241     | Donnie Alley                |
      | 244     | Dorado Notting              |
      | 253     | Drifter Commandments        |
      | 255     | Driving Polish              |
      | 263     | Durham Panky                |
      | 265     | Dying Maker                 |
      | 266     | Dynamite Tarzan             |
      | 267     | Eagles Panky                |
      | 272     | Edge Kissing                |
      | 273     | Effect Gladiator            |
      | 276     | Element Freddy              |
      | 280     | Empire Malkovich            |
      | 291     | Evolution Alter             |
      | 295     | Expendable Stallion         |
      | 296     | Express Lonely              |
      | 299     | Factory Dragon              |
      | 301     | Family Sweet                |
      | 303     | Fantasy Troopers            |
      | 304     | Fargo Gandhi                |
      | 305     | Fatal Haunted               |
      | 313     | Fidelity Devil              |
      | 317     | Fireball Philadelphia       |
      | 321     | Flash Wars                  |
      | 322     | Flatliners Killer           |
      | 327     | Fool Mockingbird            |
      | 330     | Forrester Comancheros       |
      | 331     | Forward Temple              |
      | 341     | Frost Head                  |
      | 342     | Fugitive Maguire            |
      | 347     | Games Bowfinger             |
      | 349     | Gangs Pride                 |
      | 350     | Garden Island               |
      | 356     | Giant Troopers              |
      | 358     | Gilmore Boiled              |
      | 360     | Glass Dying                 |
      | 361     | Gleaming Jawbreaker         |
      | 366     | Goldfinger Sensibility      |
      | 367     | Goldmine Tycoon             |
      | 369     | Goodfellas Salute           |
      | 376     | Grapes Fury                 |
      | 378     | Greatest North              |
      | 382     | Grit Clockwork              |
      | 391     | Half Outfield               |
      | 392     | Hall Cassidy                |
      | 394     | Hamlet Wisdom               |
      | 403     | Harry Idaho                 |
      | 408     | Head Stranger               |
      | 409     | Heartbreakers Bright        |
      | 412     | Heavyweights Beast          |
      | 417     | Hills Neighbors             |
      | 418     | Hobbit Alien                |
      | 427     | Homeward Cider              |
      | 428     | Homicide Peach              |
      | 433     | Horn Working                |
      | 434     | Horror Reign                |
      | 439     | Hunchback Impossible        |
      | 444     | Hustler Party               |
      | 447     | Ice Crossing                |
      | 455     | Impossible Prejudice        |
      | 460     | Innocent Usual              |
      | 464     | Intentions Empire           |
      | 467     | Intrigue Worst              |
      | 468     | Invasion Cyclone            |
      | 484     | Jerk Paycheck               |
      | 486     | Jet Neighbors               |
      | 489     | Juggler Hardly              |
      | 494     | Karate Moon                 |
      | 500     | Kiss Glory                  |
      | 502     | Knock Warlock               |
      | 504     | Kwai Homeward               |
      | 506     | Lady Stage                  |
      | 510     | Lawless Vision              |
      | 521     | Lies Treatment              |
      | 525     | Loathing Legally            |
      | 529     | Lonely Elephant             |
      | 531     | Lose Inch                   |
      | 535     | Love Suicides               |
      | 542     | Lust Lock                   |
      | 545     | Madness Attacks             |
      | 554     | Malkovich Pet               |
      | 559     | Married Go                  |
      | 561     | Mask Peach                  |
      | 562     | Masked Bubble               |
      | 563     | Massacre Usual              |
      | 572     | Metropolis Coma             |
      | 573     | Microcosmos Paradise        |
      | 579     | Minds Truman                |
      | 580     | Mine Titans                 |